management:
  endpoints:
    web:
      base-path: /
  server:
    port: 8080

spring:
  application:
    name: dream-management
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail_on_unknown_properties: false
    serialization:
      fail_on_empty_beans: false
      write_dates_as_timestamps: false
    property-naming-strategy: SNAKE_CASE
